.TH "midi2dmx" "1" "0.0.0" "Me" "dmx tools"
.SH "NAME"
.LP 
midi2dmx \- convert midi messages to dmx
.SH "SYNTAX"
.LP 
midi2dmx
[\fI\-\-dmx\fP <\fIdevice\fP>] 
[\fI\-\-midi\fP <\fIdevice\fP>] 
[\fI\-\-noteoffset\fP <\fIint\fP>] 
[\fI\-\-controlleroffset\fP <\fIint\fP>] 
[\fI\-\-help\fP] 
.br 
.SH "DESCRIPTION"
.LP 
midi2dmx will translate midi messages to dmx slots.
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-dmx\fR <\fIdevice\fP>
Use device for dmx output. default /dev/dmx and /dev/misc/dmx
.TP 
\fB\-\-midi\fR <\fIdevice\fP>
Use device for midi input. default /dev/midi
.TP 
\fB\-\-noteoffset\fR <\fIint\fP>
Add int to every note to get dmx slot. int can be negative.
.TP 
\fB\-\-controlleroffset\fR <\fIint\fP>
Add int to every controller to get dmx slot. int can be negative.
.TP 
\fB\-\-help\fR
print command line usage.


.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBDMX\fP
Specifies the default dmx device
.SH "AUTHORS"
.LP 
Dirk Jagdmann <doj@cubic.org>
